Add ADS8688
LibrePCB-Libraries/Texas_Instruments.lplib pull request #7
Opened 2020-04-24 20:05 UTC by matejx

##### SUMMARY
Added TI ADS8688 symbol+component+device

##### OPEN QUESTIONS / UNRESOLVED ISSUES

##### CHECKLIST

- [x ] I have read and followed the [library conventions](https://docs.librepcb.org/#libraryconventions).
- [ ] For packages, I followed IPC7351C (see details in library conventions).
- [x ] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x ] I agree to publish all my changes under the [CC0 Public Domain License](https://en.wikipedia.org/wiki/CC0), allowing everyone to use and modify the content without any restrictions.

2020-05-05 20:53 UTC, dbrgn requested changes
Great, thanks for the contribution! Looks clean. Some notes:

- It seems that the datasheet recommends decoupling all AIN pins with a capacitor. Thus, I'd recommend doubling the spacing of those pins so that you can directly put a capacitor between a pair (the symbol has 5.08 spacing).
- For the same reason, space out REFIO/REFCAP/REFGND, AVDD/AGND, DVDD/DGND and AUX_IN/AUX_GND. The symbol will be less compact, but schematics will look better.

Regarding the pinout, do you have a reliable source? [That datasheet](http://www.ti.com/lit/ds/symlink/ads8688.pdf?ts=1588710326429) is the worst thing I've ever seen. Sometimes the description has pin names swapped. And while the pin functions table lists pin 3 as DAISY and pin 4 as nREFSEL, the layout example has them the other way around:

![2020-05-05-224826_956x446_scrot](https://user-images.githubusercontent.com/105168/81114641-b6fe4a80-8f22-11ea-9003-f7c6d90c4930.png)

Apparently in the 5 years since that was published, either nobody complained or they just didn't bother to fix it.

2020-05-05 20:53 UTC, dbrgn commented on sym/13e747a6-3ce1-4722-a18e-4fc469c491b0/symbol.lp
> + (name "ADS8868")
Typo, this should probably be 8688.

```suggestion
 (name "ADS8688")
```

2020-05-05 20:53 UTC, dbrgn commented on sym/13e747a6-3ce1-4722-a18e-4fc469c491b0/symbol.lp
> + (pin 809f7f16-6b76-4d9d-94bd-bfd3b673c67e (name "AIN0_P")
More of a comment, not a change request: The datasheet inconsistently names the analog pins (e.g. `AIN_6P` but `AIN2_GND`). I guess `AINx_(P|GND)` makes most sense.

Edit: Woah, that datasheet is horrible. Sometimes they even mix up the pin names in the descriptions...

2020-05-31 17:32 UTC, matejx commented
I made the requested changes. I'm unsure how to proceed with the pull request, please advise.

The error in the datasheet was noticed by someone in 2018 and acknowledged by TI:

https://e2e.ti.com/support/data-converters/f/73/t/705308?ADS8688A-Possible-Pinout-Errata-in-Datasheet-Diagram

i.e. the suggested layout is wrong, the pin description is right.

2020-10-02 21:25 UTC, dbrgn approved these changes
Thanks for the errata link and the fixes! Looking great now, sorry for the long delay in reviewing.

2020-10-02 21:25 UTC, merged